---
language: python
services: docker

env:
  matrix:
    # Test defaults.
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1804

install:
  # Install test dependencies.
  - pip install molecule docker

script:
  # Run tests.
  - molecule test --all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
