---
- name: Download and install rubygems (RedHat)
  ansible.builtin.package:
    name: rubygems
    state: present
  when: ansible_os_family == "RedHat"
  retries: 5
  delay: 5

- name: Run "apt-get update" (Debian)
  ansible.builtin.apt:
    update_cache: true
  when: ansible_os_family == "Debian"
  retries: 5
  delay: 5

- name: Download and install Ruby (Debian)
  ansible.builtin.package:
    name: ruby
    state: present
  when: ansible_os_family == "Debian"
  retries: 5
  delay: 5

- name: Download and install the facter Gem
  community.general.gem:
    name: facter
    state: present
    version: "{{ facter_version }}"
    user_install: false
    norc: true
  retries: 5
  delay: 5

- name: Create a symbolic link for /usr/bin/facter (RedHat)
  ansible.builtin.file:
    src: /usr/local/bin/facter
    dest: /usr/bin/facter
    owner: root
    group: root
    state: link
  when: ansible_os_family == "RedHat"

- name: Rerun setup module to gather facts
  ansible.builtin.setup:
    gather_subset:
      - facter
