---
- name: Download and install epel (yum)
  package:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"

- name: Download and install factor
  package:
    name: facter
    state: present

- name: Rerun setup to gather the new facter facts
  action: setup