---
- name: Download and install rubygems (RedHat)
  package:
    name: rubygems
    state: present
  when: ansible_os_family == "RedHat"

- name: Run "apt-get update" (Debian)
  apt:
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Download and install Ruby (Debian)
  package:
    name: ruby
    state: present
  when: ansible_os_family == "Debian"

- name: Download and install the facter Gem
  gem:
    name: facter
    state: present
    version: "{{ facter_version }}"
    user_install: false

- name: Create a symbolic link for /usr/bin/facter (RedHat)
  file:
    src: /usr/local/bin/facter
    dest: /usr/bin/facter
    owner: root
    group: root
    state: link
  when: ansible_os_family == "RedHat"

- name: Rerun setup to gather the new facter facts
  action: setup
