---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: ansible-role-facter

  post_tasks:
    - name: Fail if facter_facterversion is not defined
      fail:
        msg: Facter is Not Working
      when: facter_facterversion is not defined
